# Generated by Django 3.2.15 on 2022-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, help_text="Url de la page (laisser vide pour la page d'acceuil)", unique=True, verbose_name='url')),
                ('content', models.TextField(help_text='Contenu de la page (au format HTML, avec les balises templates django)')),
                ('visible', models.BooleanField(default=True, help_text='Décochez pour cacher la page sans pour autant la supprimer')),
            ],
            options={
                'verbose_name': 'page HTML',
                'verbose_name_plural': 'pages HTML',
                'ordering': ['slug'],
            },
        ),
    ]
