# Generated by Django 4.1.9 on 2023-10-03 14:26

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="emailuser",
            managers=[
                ("objects", accounts.models.EmailUserManager()),
            ],
        ),
    ]
