# Generated by Django 4.2.16 on 2024-09-18 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipperAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipper_login', models.CharField(max_length=20, unique=True, verbose_name='login clipper')),
                ('unique_id', models.CharField(help_text="Les logins clipper sont rarements unique, mais le combo login+homedir l'est souvent", max_length=1023, verbose_name='identifiant unique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clipper_account', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Compte Clipper',
                'verbose_name_plural': 'Comptes Clipper',
            },
        ),
    ]
