# Generated by Django 3.2.7 on 2021-09-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activitymodel',
            name='communicate_participants',
        ),
        migrations.RemoveField(
            model_name='activitymodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='slotmodel',
            name='subscribing_open',
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='host_email',
            field=models.EmailField(max_length=254, verbose_name="email de l'organisateur"),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='must_subscribe',
            field=models.BooleanField(default=False, help_text='Informatif', verbose_name='sur inscription'),
        ),
        migrations.AlterField(
            model_name='slotmodel',
            name='color',
            field=models.CharField(choices=[('a', 'Rouge'), ('b', 'Orange'), ('c', 'Jaune'), ('d', 'Vert'), ('e', 'Bleu'), ('f', 'Bleu foncé'), ('g', 'Noir')], default='a', help_text='La légende des couleurs est modifiable dans les paramètres', max_length=1, verbose_name='Couleur'),
        ),
        migrations.DeleteModel(
            name='ActivityChoicesModel',
        ),
        migrations.DeleteModel(
            name='ParticipantModel',
        ),
    ]
