# Generated by Django 3.2.16 on 2022-11-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='nb_murder',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de murder réalisées'),
        ),
    ]
