# Generated by Django 3.0.8 on 2021-03-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interludesactivity',
            name='canonical',
            field=models.ForeignKey(blank=True, help_text="Si plusieurs copie d'une activité existe (pour plusieurs crénaux), et une seule est affichée, sélectionner là dans les copie pour réparer les liens du planning vers la description", null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.InterludesActivity', verbose_name='Représentant canonique'),
        ),
        migrations.AddField(
            model_name='interludesactivity',
            name='desc_as_html',
            field=models.BooleanField(default=False, help_text='Assurer vous que le texte est bien formaté, cette option peut casser la page activités.', verbose_name='Description au format HTML'),
        ),
        migrations.AddField(
            model_name='interludesactivity',
            name='subscribing_open',
            field=models.BooleanField(default=False, help_text="Si vrai, apparaît dans la liste du formulaire d'inscription", verbose_name='ouverte aux inscriptions'),
        ),
        migrations.AlterField(
            model_name='interludesactivity',
            name='description',
            field=models.TextField(help_text='Texte ou html selon la valeur de "Description HTML".\n', max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='interludesactivity',
            name='display',
            field=models.BooleanField(default=False, help_text="Si vrai, s'affiche sur la page activités", verbose_name='afficher dans la liste'),
        ),
        migrations.AlterField(
            model_name='interludesactivity',
            name='must_subscribe',
            field=models.BooleanField(default=False, help_text="Informatif, il faut utiliser 'ouverte aux inscriptions' pour ajouter dans la liste d'inscription", verbose_name='sur inscription'),
        ),
    ]
