# Generated by Django 4.2.16 on 2024-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='option1',
            field=models.BooleanField(default=False, verbose_name='option 1'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='option2',
            field=models.BooleanField(default=False, verbose_name='option 2'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='option3',
            field=models.BooleanField(default=False, verbose_name='option 3'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='option4',
            field=models.BooleanField(default=False, verbose_name='option 4'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='option5',
            field=models.BooleanField(default=False, verbose_name='option 5'),
        ),
    ]
