# Generated by Django 3.2.7 on 2021-09-20 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210920_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveIntegerField(verbose_name='table')),
                ('time', models.DateTimeField(verbose_name='date et heure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'adjacence',
                'verbose_name_plural': 'adjacences',
            },
        ),
    ]
