# Generated by Django 4.2.16 on 2024-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_participantmodel_option1_participantmodel_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='duration',
            field=models.DurationField(help_text='format hh:mm:ss (ou j hh:mm:ss)', verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='slotmodel',
            name='duration',
            field=models.DurationField(blank=True, help_text="Format hh:mm:ss (ou j hh:mm:ss). Laisser vide pour prendre la durée de l'activité correspondante", null=True, verbose_name='durée'),
        ),
    ]
