# Generated by Django 3.0.8 on 2021-04-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210407_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interludesactivity',
            name='description',
            field=models.TextField(help_text='Texte ou html selon la valeur de "Description HTML".\n', max_length=10000, verbose_name='description'),
        ),
    ]
