# Generated by Django 3.2.7 on 2021-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_adjacencymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjacencymodel',
            options={'verbose_name': 'présence'},
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='show_email',
            field=models.BooleanField(default=True, help_text="Si l'affichage d'email global et cette case sont vrai, affiche l'email de l'orga", verbose_name="afficher l'email de l'orga"),
        ),
    ]
