# Generated by Django 3.2.16 on 2022-11-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_activitymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='payé(e)'),
        ),
    ]
