# Generated by Django 3.2.7 on 2021-09-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210925_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmodel',
            name='on_activity',
            field=models.BooleanField(default=True, verbose_name="afficher dans la description de l'activité"),
        ),
        migrations.AlterField(
            model_name='slotmodel',
            name='on_planning',
            field=models.BooleanField(default=True, verbose_name='afficher sur le planning'),
        ),
    ]
