# Generated by Django 4.1.3 on 2022-12-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_participantmodel_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantmodel",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="salarié(e)"),
        ),
    ]
