# Generated by Django 3.2.7 on 2021-09-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210927_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacencymodel',
            name='type',
            field=models.CharField(choices=[('0', 'Non-spécifié'), ('1', 'Début de partie'), ('2', 'Rejoins une partie')], default='0', max_length=1, verbose_name='type'),
        ),
    ]
