# Generated by Django 3.0.8 on 2021-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210425_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='interludesslot',
            name='duration',
            field=models.DurationField(blank=True, help_text="Format 00:00:00. Laisser vide pour prendre la durée de l'activité correspondante", null=True, verbose_name='durée'),
        ),
    ]
