# Generated by Django 3.2.16 on 2022-12-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221209_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant payé'),
        ),
    ]
