# Generated by Django 4.1.9 on 2023-05-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_participantmodel_paid'),
        ('home', '0006_participantmodel_amount_paid'),
    ]

    operations = [
    ]
