# Generated by Django 3.0.14 on 2021-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_interludesslot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interludesslot',
            name='color',
            field=models.CharField(choices=[('a', 'Rouge'), ('b', 'Orange'), ('c', 'Jaune'), ('d', 'Vert'), ('e', 'Bleu'), ('f', 'Bleu foncé'), ('g', 'Noir')], default='f', help_text='La légende des couleurs est modifiable dans les paramètres', max_length=1, verbose_name='Couleur'),
        ),
    ]
