# Generated by Django 3.2.15 on 2022-09-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_adjacencymodel_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdjacencyModel',
        ),
    ]
