# Generated by Django 5.1 on 2024-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20230528_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='extra_contact',
            field=models.CharField(blank=True, help_text="(Optionel) sera communiqué au MJ pour faciliter l'organisation", max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='murder_comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Info pour MJ'),
        ),
    ]
