# Generated by Django 4.1.1 on 2022-09-10 09:48

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_adjacencymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='year',
            field=models.IntegerField(default=home.models.get_year, help_text='Année des 48h des jeux cette activité (purement informatif)', verbose_name='année'),
        ),
    ]
