# Generated by Django 4.2.16 on 2024-10-20 13:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_participantmodel_extra_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='year',
            field=models.IntegerField(default=home.models.get_year, help_text="Année de l'édition des interludes (ex: 2025 pour 2024-2025)", verbose_name='année'),
        ),
    ]
