# Generated by Django 3.2.7 on 2021-09-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='activities_allocated',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='inscriptions_end',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='inscriptions_open',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='inscriptions_start',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='orga_notified',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='user_notified',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_host_emails',
            field=models.BooleanField(default=False, help_text='Ces mail sont affichés sur la page activités pour que les gens puissent les contacter', verbose_name="Afficher les mails des orgas d'activités"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='allow_mass_mail',
            field=models.BooleanField(default=False, help_text="Par sécurité, n'activez ceci qu'au moment d'envoyer les emails et désactivez le après", verbose_name="Permettre l'envoi de mails à tous les utilisateurs"),
        ),
    ]
