# Generated by Django 3.2.16 on 2022-11-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_hosting_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='activity_inscriptions_open',
            field=models.BooleanField(default=False, help_text="Permet d'ouvrir la partie du formulaire d'inscription pour les activités (nécessite l'ouverture des inscriptions)", verbose_name="Ouvrir l'inscription aux activitées"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='inscriptions_open',
            field=models.BooleanField(default=False, help_text="Permet d'ouvrir le formulaire d'inscription (repas et dodo; l'inscription aux activité est ouvrable en plus)", verbose_name='Ouvrir les inscriptions'),
        ),
    ]
