# Generated by Django 3.2.7 on 2021-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20210920_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='table_nb',
            field=models.PositiveIntegerField(default=0, help_text="Permet le scan de QR codes pour les urls '/table/0' ... '/table/&lt;n-1&gt;'", verbose_name='Nombre de tables'),
        ),
    ]
