# Generated by Django 4.2.16 on 2025-01-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sponsormodel_sitesettings_option1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meal_inscriptions_open',
            field=models.BooleanField(default=True, help_text="Permet de s'inscrire aux repas sur le formulaire d'inscription.", verbose_name="Ouvrir l'inscription aux repas"),
        ),
    ]
