# Generated by Django 4.1.3 on 2022-12-02 11:42

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_auto_20221108_1919"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="affiche",
            field=models.FileField(
                blank=True,
                null=True,
                storage=site_settings.models.OverwriteStorage("AfficheInterludes"),
                upload_to="",
                verbose_name="Affiche",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ticket_url",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Lien billeterie"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="planning_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=site_settings.models.OverwriteStorage("PlanningInterludes"),
                upload_to="",
                verbose_name="Version PDF du planning",
            ),
        ),
    ]
