# Generated by Django 4.2.16 on 2025-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_meal_inscriptions_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sleep_inscriptions_open',
            field=models.BooleanField(default=True, help_text="Permet de s'inscrire à l'hébergement sur le formulaire d'inscription.", verbose_name="Ouvrir l'inscription à l'hébergement"),
        ),
    ]
