# Generated by Django 3.2.15 on 2022-09-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20210926_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='table_nb',
        ),
    ]
