# Generated by Django 3.0.8 on 2021-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20210407_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='planning_caption',
            field=models.TextField(blank=True, help_text='Légende du planning (au format HTML). Les couleurs sont accessibles dans le stylevia var(--color_1), var(--color_1_fg) et var(--color_1_hover)', null=True, verbose_name='Légende du planning'),
        ),
    ]
