# Generated by Django 4.1.1 on 2022-09-09 09:26

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_remove_sitesettings_table_nb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='affiche',
            field=models.FileField(blank=True, null=True, storage=site_settings.models.OverwriteStorage('Affiche48hDesJeux'), upload_to='', verbose_name='Affiche'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='planning_file',
            field=models.FileField(blank=True, help_text='Pour affichage sur mobile', null=True, storage=site_settings.models.OverwriteStorage('Planning48hDesJeux'), upload_to='', verbose_name='Version PDF du planning'),
        ),
    ]
