# Generated by Django 3.0.8 on 2021-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_planning_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='planning_caption',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='planning_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Version PDF du planning'),
        ),
    ]
