# Generated by Django 3.0.8 on 2021-04-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_planning_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='planning_caption',
        ),
    ]
