# Generated by Django 4.1.9 on 2023-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0005_sitesettings_meal_sunday_evening_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="notify_on_activity_submission",
            field=models.BooleanField(
                default=True,
                help_text="Envoie un email aux administrateurs quand une nouvelle activité est ajoutée via le formulaire.",
                verbose_name="Notification d'ajout d'activité",
            ),
        ),
    ]
