# Generated by Django 4.1.13 on 2024-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_affiche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_on_activity_submission',
            field=models.BooleanField(default=True, help_text="Envoie un email (à l'email de contact) quand une nouvelle activité est ajoutée via le formulaire.", verbose_name="Notification d'ajout d'activité"),
        ),
    ]
