# Generated by Django 3.0.8 on 2021-04-28 12:46

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20210425_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='planning_file',
            field=models.FileField(blank=True, null=True, storage=site_settings.models.OverwriteStorage(), upload_to='', verbose_name='Version PDF du planning'),
        ),
    ]
