# Generated by Django 3.0.14 on 2021-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20210428_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='caption_black',
            field=models.CharField(blank=True, default='Autre', max_length=200, null=True, verbose_name='Légende planning (noir)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='caption_blue',
            field=models.CharField(blank=True, default='Événements de début et fin', max_length=200, null=True, verbose_name='Légende planning (bleu)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='caption_dark_blue',
            field=models.CharField(blank=True, default='Jeux vidéos', max_length=200, null=True, verbose_name='Légende planning (bleu foncé)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='caption_green',
            field=models.CharField(blank=True, default='Tournois', max_length=200, null=True, verbose_name='Légende planning (vert)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='caption_orange',
            field=models.CharField(blank=True, default='Jeux de rôle sur table', max_length=200, null=True, verbose_name='Légende planning (orange)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='caption_red',
            field=models.CharField(blank=True, default='Jeux de rôle grandeur nature', max_length=200, null=True, verbose_name='Légende planning (rouge)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='caption_yellow',
            field=models.CharField(blank=True, default='Activités libres', max_length=200, null=True, verbose_name='Légende planning (jaune)'),
        ),
    ]
