# Generated by Django 4.2.16 on 2024-10-12 14:55

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_favicon_sitesettings_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='price_sunday_meal_paid',
            new_name='price_sunday_evening_meal_paid',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='price_sunday_meal_unpaid',
            new_name='price_sunday_evening_meal_unpaid',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='price_meal_paid',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='price_meal_unpaid',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meal_friday_evening',
            field=models.BooleanField(default=True, verbose_name='Repas vendredi soir'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meal_saturday_evening',
            field=models.BooleanField(default=True, verbose_name='Repas samedi soir'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meal_saturday_midday',
            field=models.BooleanField(default=True, verbose_name='Repas samedi midi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meal_saturday_morning',
            field=models.BooleanField(default=True, verbose_name='Repas samedi matin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meal_sunday_midday',
            field=models.BooleanField(default=True, verbose_name='Repas dimanche midi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meal_sunday_morning',
            field=models.BooleanField(default=True, verbose_name='Repas dimanche matin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_friday_evening_meal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du vendredi soir (salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_friday_evening_meal_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du vendredi soir (non-salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_saturday_evening_meal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du samedi soir (salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_saturday_evening_meal_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du samedi soir (non-salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_saturday_midday_meal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du samedi midi (salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_saturday_midday_meal_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du samedi midi (non-salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_saturday_morning_meal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du samedi matin (salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_saturday_morning_meal_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du samedi matin (non-salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_sunday_midday_meal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du dimanche midi (salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_sunday_midday_meal_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du dimanche midi (non-salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_sunday_morning_meal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du dimanche matin (salarié)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_sunday_morning_meal_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='prix du repas du dimanche matin (non-salarié)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meal_sunday_evening',
            field=models.BooleanField(default=True, verbose_name='Repas dimanche soir'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='planning_file',
            field=models.FileField(blank=True, help_text="Le planning autogénéré n'est pas très lisible sur mobile. Je conseille d'en faire une capture sur grand écran et l'ajouter ici.", null=True, storage=site_settings.models.OverwriteStorage('PlanningInterludes'), upload_to='', verbose_name='Version image ou PDF du planning'),
        ),
    ]
