# Generated by Django 5.1 on 2024-08-23 16:35

import site_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_notify_on_activity_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Icône du site, image au format .ico', null=True, storage=site_settings.models.OverwriteStorage('favicon'), upload_to='', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, help_text='Apparait dans le header', null=True, storage=site_settings.models.OverwriteStorage('LogoInterludes'), upload_to='', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sleep_host_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Lien du formulaire de proposition d'hébergement"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sleeper_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Lien du formulaire de demande d'hébergement"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hosting_school',
            field=models.CharField(choices=[('U', 'ENS Ulm'), ('L', 'ENS Lyon'), ('R', 'ENS Rennes'), ('C', 'ENS Paris Saclay')], default='U', max_length=1, verbose_name="École hébergeant l'événement"),
        ),
    ]
